# Generated by Django 5.2.10 on 2026-01-19 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Command',
            fields=[
                ('pk_command_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('CMD_PING', 'Ping'), ('CMD_SHELL_EXEC', 'Shell Execution'), ('CMD_OPEN_BROWSER', 'Open Browser'), ('CMD_SCREENSHOT', 'Screenshot'), ('CMD_SYSTEM_INFO', 'System Info'), ('CMD_LOCK_PC', 'Lock PC'), ('CMD_SHUTDOWN', 'Shutdown'), ('CMD_RESTART', 'Restart'), ('CMD_SCHEDULED_SHUTDOWN', 'Scheduled Shutdown'), ('CMD_SET_VOLUME', 'Set Volume'), ('CMD_OPEN_PRESET', 'Open Preset')], max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Client'), ('QUEUED', 'Queued on Client'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Device',
            fields=[
                ('pk_device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hardware_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os_config', models.JSONField(blank=True, default=dict)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Preset',
            fields=[
                ('pk_preset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_CommandLog',
            fields=[
                ('pk_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output', models.TextField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='api.tbl_command')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='api.tbl_device'),
        ),
    ]
