# Generated by Django 5.2.10 on 2026-01-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_command',
            name='command_type',
            field=models.CharField(choices=[('CMD_PING', 'Ping'), ('CMD_SHELL_EXEC', 'Shell Execution'), ('CMD_OPEN_BROWSER', 'Open Browser'), ('CMD_SCREENSHOT', 'Screenshot'), ('CMD_SYSTEM_INFO', 'System Info'), ('CMD_LOCK_PC', 'Lock PC'), ('CMD_SHUTDOWN', 'Shutdown'), ('CMD_RESTART', 'Restart'), ('CMD_SCHEDULED_SHUTDOWN', 'Scheduled Shutdown'), ('CMD_SET_VOLUME', 'Set Volume'), ('CMD_OPEN_PRESET', 'Open Preset'), ('CMD_MEDIA', 'Media Control')], max_length=50),
        ),
    ]
