# Generated by Django 5.2.13 on 2026-05-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tbl_command_command_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_command',
            name='command_type',
            field=models.CharField(choices=[('CMD_PING', 'CMD_PING'), ('CMD_SHELL_EXEC', 'CMD_SHELL_EXEC'), ('CMD_OPEN_BROWSER', 'CMD_OPEN_BROWSER'), ('CMD_SCREENSHOT', 'CMD_SCREENSHOT'), ('CMD_SYSTEM_INFO', 'CMD_SYSTEM_INFO'), ('CMD_LOCK_PC', 'CMD_LOCK_PC'), ('CMD_SHUTDOWN', 'CMD_SHUTDOWN'), ('CMD_RESTART', 'CMD_RESTART'), ('CMD_SCHEDULED_SHUTDOWN', 'CMD_SCHEDULED_SHUTDOWN'), ('CMD_SET_VOLUME', 'CMD_SET_VOLUME'), ('CMD_OPEN_PRESET', 'CMD_OPEN_PRESET'), ('CMD_MEDIA', 'CMD_MEDIA'), ('CMD_LIST_PROCESSES', 'CMD_LIST_PROCESSES'), ('CMD_KILL_PROCESS', 'CMD_KILL_PROCESS'), ('CMD_CLIPBOARD_GET', 'CMD_CLIPBOARD_GET'), ('CMD_CLIPBOARD_SET', 'CMD_CLIPBOARD_SET'), ('CMD_FILE_LIST', 'CMD_FILE_LIST'), ('CMD_FILE_READ', 'CMD_FILE_READ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_command',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('QUEUED', 'QUEUED'), ('RUNNING', 'RUNNING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
