# Generated by Django 5.2.13 on 2026-05-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_new_command_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_command',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
